
version: 2
updates:
  #python dependencies from requirements.txt
  - package-ecosystem: "pip" #covers packages: dvc-data,wandb,fastapi,torch,scikit-learn,hydra-core,ruff,pytest..
    directory: "/src"
    schedule:
      interval: "weekly"
  #python frontend dependencies
  - package-ecosystem: "pip"
    directory: "/frontend"
    schedule:
      interval: "weekly"

  #Docker dependencies
  - package-ecosystem: "docker"
    directory: "/src"
    schedule:
      interval: "weekly"

  #Github actions dependencies(CI/CD workflows from .github/workflows/)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  #Pre-commit dependencies
  - package-ecosystem: "pip"
    directory: "/src"
    schedule:
      interval: "weekly"
