#python dependencies
version: 2
updates:
  - package-ecosystem: "pip" #covers packages: dvc-data,wandb,fastapi,torch,scikit-learn,hydra-core,ruff,pytest..
    directory: "/"
    schedule:
      interval: "weekly"

