
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    environment:
      - PYTHONPATH=/app

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8501:8080"
    environment:
      - FASTAPI_SERVICE_URL=http://backend:8080
    depends_on:
      - backend
