site_name: Food103Seg Calories Documentation
site_description: Food segmentation model with Full MLOPs pipeline
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
  palette:
    - scheme: default
      primary: green
      accent: orange

nav:
  - Home: index.md
  - Installation: installation.md
  - API Reference:
    - Data Module: source/data.md
    - Model Module: source/model.md
    - Training Module: source/training.md
    - Loss Functions: source/loss.md
    - Main Pipeline: source/main.md
  - Project Structure: structure.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_root_toc_entry: true
            merge_init_into_class: true
