[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "segmentation"
version = "0.1.0"
authors = [{name = "XYZ", email = "me@em.com"}]
description = "A Python package for food segmentation tasks"
requires-python = ">=3.8"
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.setuptools]
packages = ["src.segmentation"]

[project.scripts]
train = "src.segmentation.main:main"
