#config.yaml

defaults:
  - _self_
  - model: default
  - dataset: default

hydra:
  run:
    dir: ./configs/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ./configs/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}

# model hyperparameters
model:
  hyperparameters:
    lr: 0.001
    epochs: 1
    batch_size: 65

# experiment paths
paths:
  base_dir: /home/krrish/home/desktop/sarengeyo/food103seg-calories/


# configs/multirun/2025-07-06/14-30-15/
# ├── 0/.hydra/config.yaml         # lr=0.001 config
# ├── 1/.hydra/config.yaml         # lr=0.01 config
# ├── 2/.hydra/config.yaml         # lr=0.1 config
# └── multirun.yaml                # Summary of all runs
