#config.yaml

defaults:
  - _self_
  - model: default
  - dataset: default

hydra:
  run:
    dir: ./configs/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ./configs/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}

# model hyperparameters
model:
  hyperparameters:

    lr: 0.001
    epochs: 25
    batch_size: 32


# experiment paths
paths:
  base_dir: /home/krrish/home/desktop/sensor-behaviour

# simple profiling
profiling:
  enabled: false
  log_dir: ./profiler_logs
