program: wandb_runner.py
method: bayes
metric:
  name: Test Loss
  goal: minimize

parameters:
  lr:
    min: 0.0001
    max: 0.01
  batch_size:
    values: [16, 32, 64]
  epochs:
    values: [5]

project: Food-Segmentation
run_cap: 20

early_terminate:
  type: hyperband
  min_iter: 1
